version: '2.2.2'
services:
  node:
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  nginx:
    image: nginx
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./web:/usr/share/nginx/html
    ports:
      - 80:80
  mongoku:
    image: huggingface/mongoku
    depends_on:
      - mongo
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://mongo:27017
    ports:
      - 3100:3100
  mongoseed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./data/doc:/mongo-seed
    command: /mongo-seed/import.sh
